services:
  - type: web
    name: multiplayer-minigames
    runtime: node
    rootDir: minigames-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://davibarberini.github.io
